# Generated by Django 3.1.7 on 2021-02-23 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FetureType',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('model', models.CharField(max_length=255)),
                ('features', models.ManyToManyField(
                    blank=True, to='mining_shapes.FetureType')),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VesselProfile',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('input_image', models.ImageField(upload_to='orig_image')),
                ('segmented_image', models.ImageField(
                    upload_to="seg_images")),
                ('catalog', models.CharField(max_length=255)),
                ('session', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='mining_shapes.session')),
            ],
        ),
    ]
