# Generated by Django 3.1.7 on 2021-02-22 09:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mining_shapes', '0002_remove_vesselprofile_segmented_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FetureType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='model',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='features',
            field=models.ManyToManyField(blank=True, to='mining_shapes.FetureType'),
        ),
    ]
