# Generated by Django 3.1.7 on 2021-02-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining_shapes', '0002_auto_20210223_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segmentationimage',
            name='image',
            field=models.ImageField(upload_to='seg_images'),
        ),
        migrations.AlterField(
            model_name='vesselprofile',
            name='segmented_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
